### PR TITLE
Review

### PR DESCRIPTION
**Pull request by Wiz2101**

### CODE REVIEW

**Comment by lhsang** [comment]
image
Got an error when you click your process without login

**Comment by lhsang** [comment]
image
validate

**Comment by Wiz2101** [comment]
> click

**Comment by lhsang** [comment]
image
correct permission

**Comment by Wiz2101** [comment]
> image Got an error when you click your process without login

According to last discussion, me and Nhi agreed to separate Login & Order into 2 process. And we also need to login initally, so we have to access login process first

**Comment by NhyNhyNguyen** [comment]
- Ui for customer order
  - Border for customer part, product part
  - Gender male, female inline
- Ui for order list
  - Datatable that shows list order should use all features of a data table sort, filter, pageable
  - Status of orders should be decorated with high line
  - Verify order error for can not get data from ws should be showed with face message
- Ui for order detail
  - Order id
   - Ui button margin top, float left or right button same with another page (example create order page, button create order in the right)
   - Document file: can't not test. **But, it should download and show the file name, can not click button upload file if don't have the file**
image

- Functionality: 
  - Login with wrong username/ password -> exception
image
  - Upload file, save order fail 
img_6
  - Enter wrong format date fail -> not show validate -> **can not create order and show message**
  - Order list page for clerk not show anything after login. **Order list for clerk should show all orders with all status** 
  - Login user customer (wiz) -> after create -> forward to the task page. **Should redirect to order list with the newest order**
  - Login user **develop** -> after creating -> forward to the task page -> User  verify the order. S**hould redirect to order list and can not verify**
img_7
img_8
 - Can verify order without ws. **Should be can not verify order from a clerk.  Document upload when creating order and should be show and can download when clerk verify that order**
- Structure: 
  - Login bean, another bean -> **user bean should not add managed bean with application scope**
  - CreateOrderDialog Data have customerDto, orderDto -> It the same why not use in OrderBean. **Should use only one place**
image
 - LoginDialog has username and password -> **should be in OrderBean not outside. CommonUtil should be removed from data class.**
image
- Verify Order dialog has Id field. **we can add in the bean**
- Process: should make the connector 90 degree
img_10

**Comment by NhyNhyNguyen** [comment]
image
image
- Length phone not 10 -> exception -> should add Facemessage if it has any exception. Handle length = 10 in client validation
image
- Ui for detail page, or verify order to big. Show resize with screen size and align center
image
- Ui for verify order (double check for create order and detail)
image
- Clerk can download if the document update by clerk and can upload new -> replace old document
image
- Currently, I can not click in icon. Only click in start 
image
- Order list is empty for clerk. -> Clerk order list page should be showed all orders. Only customer show order that they create
image
- I cheat the WS -> after verify the order cost ar
image
- Send back error, success for confirm order from customer
image
- Can not verify order. Process go to send email and throw an exception when battery is null
image
- Function for upload, download a file not work

**Comment by NhyNhyNguyen** [comment]
image
Ui text should follow the mock and scenario.

**Comment by NhyNhyNguyen** [comment]
image
ListOfOrders currently ApplicationScopes. How about a user login with a customer role and the clerk role. And with different customer users =>It will have another list of orders. It should be a request or view scope

**Comment by NhyNhyNguyen** [comment]
image
Send error, success message

**Comment by NhyNhyNguyen** [comment]
image
Order should be save total cost and show that in detail and sent back in email

**Comment by NhyNhyNguyen** [comment]
image
Update this if have time or remove html tag show only text

**Pull request closed without merging**
